#!/bin/bash

# Description: 
# This script converts Markdown files from a given directory to plaintext files.
# to be used to cleanup the pandoc command from convertDocxToMd for further processing
# Usage:
# convert_md_to_simple <input-dir> [output-dir]
# Where:
# - input-dir: The directory containing the Markdown files to be converted.
# - output-dir: Optional, specifies the directory where the plaintext files will be saved. If not provided, the script will create a new directory named 'plaintext' in the parent directory of the input directory.
# Example: convert_md_to_simple my-markdown-input  my-plaintext-output

# Check for the correct number of arguments
if [ "$#" -lt 1 ] || [ "$#" -gt 2 ]; then
    echo "Usage: $0 <input-dir> [output-dir]"
    exit 1
fi

input_dir="$1"

# If output directory is not provided, set default
if [ "$#" -eq 2 ]; then
    output_dir="$2"
else
    output_dir="${input_dir}/../plaintext"
fi

# Create output directory if it doesn't exist
mkdir -p "$output_dir"

# Iterate over .docx files in the input directory
for file in "$input_dir"/*.md; do
    # Check if it's a regular file, especially in case there are no .docx files
    if [ -f "$file" ]; then
        # Extract the base filename without the extension
        base_name=$(basename "$file" .md)
        echo $base_name
        # Run pandoc command
        sed 's/\\//g' "$file" > "$output_dir/${base_name}.md"
        #pandoc -s "$file" --wrap=none -t plain -o "$output_dir/${base_name}.txt"
    fi
done

echo "Conversion finished."

