#!/usr/bin/env python3

import os
import sys

def create_files_with_string_in_cwd(string):
    cwd = os.getcwd()
    for filename in os.listdir(cwd):
        if os.path.isfile(filename):
            new_filename = f"{os.path.splitext(filename)[0]}.txt"
            with open(new_filename, 'w') as f:
                f.write(string)
            print(f"Created {new_filename}")

if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: create_text_tags <string>")
        sys.exit(1)
    
    string = sys.argv[1]
    create_files_with_string_in_cwd(string)

