#!/bin/bash
prompt_confirm() {
  while true; do
    read -r -n 1 -p "${1:-Continue?} [y/n]: " REPLY
    case $REPLY in
      [yY]) echo ; return 0 ;;
      [nN]) echo ; return 1 ;;
      *) printf " \033[31m %s \n\033[0m" "invalid input"
    esac 
  done  
}

prompt_confirm "Are you sure you want to reconfigure grub automatically?" || exit 0

sudo sed -i '/^GRUB_DEFAULT.*$/d;/^GRUB_SAVEDEFAULT.*$/d' /etc/default/grub
sudo bash -c 'echo -e "GRUB_SAVEDEFAULT=true\nGRUB_DEFAULT=saved" >> /etc/default/grub'
sudo update-grub
