#!/bin/bash
shopt -s nocaseglob
mkdir h264res
for filename in *.{mp4,mkv,mov,mts}; do
    [ -f "$filename" ] || continue
    destination="h264res/${filename%.*}.mp4"
    ffmpeg -i "$filename" -vcodec libx264 -c:a aac -b:a 256k -movflags use_metadata_tags -crf ${2:-22} -s ${1:-1920x1080} "$destination"
    # -c:a aac -b:a 256k 
    touch -r "$filename" "$destination"
done
exit 0
