#!/bin/bash
shopt -s nocaseglob
mkdir rh265
for filename in *.mp4; do
    [ -f "$filename" ] || break
    destination="rh265/${filename%.*}.mp4"
    ffmpeg -i "$filename" -c:v libx265 -c:a aac -b:a 256k -movflags use_metadata_tags -crf ${2:-20} -s ${1:-1920x1080} "$destination"
    touch -r "$filename" "$destination"
done
exit 0