#!/bin/bash
shopt -s nocaseglob
mkdir h265
for filename in *.{mp4,mkv,mov,mts,webm,avi}; do
    [ -f "$filename" ] || continue
    destination="h265/${filename%.*}.mp4"
    #ffmpeg -i "$filename" -c:v libx265 -c:a aac -b:a 256k -movflags use_metadata_tags -crf ${1:-20} "$destination"
    ffmpeg -i "$filename" -vf "eq=saturation=1.2" -c:v hevc_nvenc -preset slow -rc vbr -cq ${1:-22} -b:v 0 -c:a aac -b:a 256k -movflags use_metadata_tags "$destination" #-rc vbr_hq
    touch -r "$filename" "$destination"
done
exit 0
