#!/bin/bash
shopt -s nocaseglob
mkdir h265res
for filename in *.{mp4,mkv,mov,mts,webm}; do
    [ -f "$filename" ] || continue
    destination="h265res/${filename%.*}.mp4"
    ffmpeg -i "$filename" -c:v libx265 -c:a aac -b:a 256k -movflags use_metadata_tags -crf ${2:-20} -s ${1:-1920x1080} "$destination"
    touch -r "$filename" "$destination"
done
exit 0
