#!/bin/bash

# renames all the files in the current dir to their md5 hashes, will get rid of duplicate files.

read -p "Are you sure? " -n 1 -r
echo    # (optional) move to a new line
if [[ ! $REPLY =~ ^[Yy]$ ]]
then
    [[ "$0" = "$BASH_SOURCE" ]] && exit 1 || return 1 # handle exits from shell or function but don't exit interactive shell
fi


shopt -s nocaseglob
mkdir renamed
for file in *; do
    if [ ! -d "$x" ]; then
        hash=$(md5sum "${file}"|cut -d' ' -f1)
        ext=${file##*.}
        cp -v "$file" "renamed/${hash}.${ext}"
    fi
done
exit 0
